export const MOBILE_SET = "MOBILE_SET";
export const SEARCH_MODAL_SET = "SEARCH_MODAL_SET";
export const PERSONAL_DATA_SET = "PERSONAL_DATA_SET";
export const INTAKE_LIST_SET = "INTAKE_LIST_SET";
export const DATE_SET = "DATE_SET";
export const CALORIES_SET = "CALORIES_SET";
export const LOADING_SEARCH_SET = "LOADING_SEARCH_SET";
export const SEARCH_ITEMS_SET = "SEARCH_ITEMS_SET";
